Updating github action + test

diff --git a/.github/workflows/update-pricing.yml b/.github/workflows/update-pricing.yml
--- a/.github/workflows/update-pricing.yml
+++ b/.github/workflows/update-pricing.yml
@@ -33,7 +33,9 @@ jobs:
                 git diff --no-index --stat ellmer/data-raw/prices.json main/chatlas/data/prices.json
                 if [[ -n $(git diff chatlas/types) ]]; then
                     echo "Changes detected:"
-
+                    echo "::error::Ellmer's prices.json does not match the current Chatlas prices.json"
+                    exit 1
+                fi
 
 
                 
